// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqoW90NdHg3bDPUrBLvWCpGESVWK9iRxI',
    appId: '1:583037855172:web:7b380c20c2a1720f58b091',
    messagingSenderId: '583037855172',
    projectId: 'book-flutter-data',
    authDomain: 'book-flutter-data.firebaseapp.com',
    storageBucket: 'book-flutter-data.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADpzjKvBzAJsV3juBNCP5j7iPVWXca2vU',
    appId: '1:583037855172:android:dc4addc42fc6f67e58b091',
    messagingSenderId: '583037855172',
    projectId: 'book-flutter-data',
    storageBucket: 'book-flutter-data.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9O1xc4mjkcgnR-Qq1vw8dWJng5WxoRo4',
    appId: '1:583037855172:ios:fcd9a61404abfe9358b091',
    messagingSenderId: '583037855172',
    projectId: 'book-flutter-data',
    storageBucket: 'book-flutter-data.appspot.com',
    iosBundleId: 'com.example.flutterBookMall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9O1xc4mjkcgnR-Qq1vw8dWJng5WxoRo4',
    appId: '1:583037855172:ios:f47f013fda1168a458b091',
    messagingSenderId: '583037855172',
    projectId: 'book-flutter-data',
    storageBucket: 'book-flutter-data.appspot.com',
    iosBundleId: 'com.example.flutterBookMall.RunnerTests',
  );
}
